apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f945tch0q-nodejs 
  janus-idp.io/tekton: f945tch0q-nodejs
  backstage.io/kubernetes-id: f945tch0q-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f945tch0q-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml